### PR TITLE
Add some suggested + originally planned mods

### PR DESCRIPTION
**Pull request by Speak2Erase**
Coaster mod was intended to be added, but wasn't due to a bug, and Thresh suggested adding Better records

### CODE REVIEW

**Comment by Speak2Erase** [comment]
I'm gonna add some tips in since that's something we forgot to do

**Comment by wistlyr** [comment]
k

**Comment by Speak2Erase** [comment]
nvm none of the tip mods work properly

**Comment by Speak2Erase** [comment]
Ok I think I'm done

**Comment by wistlyr** [comment]
will update tomorrow

**Comment by wistlyr** [comment]
"will update tomorrow" my ass

**Pull request merged**
