### PR TITLE
All the things

### PR DESCRIPTION
**Pull request by Speak2Erase**
After playing with hard mode on, I have decided it should be turned off since just being required to get to Barnard C is enough of a challenge
(Also the config has been tweaked to fix the Staff of power)

### CODE REVIEW

**Comment by Speak2Erase** [comment]
These commits add music discs for oneshot's ost

**Comment by Speak2Erase** [comment]
Apparently draconium drops from the ender dragon, so that's off now
**no cheating**

**Comment by Speak2Erase** [comment]
We now have the full oneshot ost + solstice ost in game

**Comment by Speak2Erase** [comment]
Don't merge this just yet I have some changes I need to make in the future (quests and whatnot)

**Comment by wistlyr** [comment]
#fixme

**Comment by Speak2Erase** [comment]
Ok that should be everything

**Comment by Speak2Erase** [comment]
nvm i take that back

**Comment by Speak2Erase** [comment]
Ok now it's done

**Comment by Speak2Erase** [comment]
This PR is finished
It adds

- Avaritia + Expansions
- Draconic additions
- A win condition
- New quests
- The entire oneshot soundtrack
- Custom recipes for certain items
- Wireless transport mods (Ender chests and tesseract)
- And some tweaks for DE

**Comment by wistlyr** [comment]
CONGRATION
YOU ARE WIENER

**Pull request merged**
